name: social
description: "Share Experience Package"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  dio: ^5.3.2
  intl: ^0.18.0
  get_storage: ^2.1.1
  logger: ^1.3.0
  shamsi_date: 0.14.1
  device_info_plus: ^9.0.2
  package_info_plus: ^5.0.1
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.4
  open_file_plus: ^3.4.1
  dartz: ^0.10.1


  # Feature packages
  responsive_framework: ^0.2.0
  flutter_svg: ^2.0.4
  loading_indicator: ^3.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  badges: ^3.1.1
  persian_number_utility: ^1.1.3
  persian_tools: ^1.0.3
  equatable: ^2.0.5
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  image_cropper: ^5.0.1
  file_picker: ^5.3.2
  flutter_cache_manager: ^3.3.1
  blur: ^3.1.0


  taakitecture:
    git:
      url: git@github.com:TaakGroup/taakitecture.git
      ref: main


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pulsator: ^1.0.0+2
  glowy_borders: ^1.0.2
  permission_handler: ^10.2.0

  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.social
        pluginClass: SocialPlugin
      ios:
        pluginClass: SocialPlugin
      web:
        pluginClass: SocialWeb
        fileName: social_web.dart


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - packages/social/assets/images/
    - packages/social/assets/fonts/
    - packages/social/assets/images/like.svg
    - packages/social/assets/images/like_fill.svg
    - packages/social/assets/images/dislike.svg
    - packages/social/assets/images/dislike_fill.svg
    - packages/social/assets/images/reply.svg
    - packages/social/assets/images/verify.svg
    - packages/social/assets/images/message_fill.svg
    - packages/social/assets/images/arrow_right.svg
    - packages/social/assets/images/gallery_add.svg
    - packages/social/assets/images/message_question.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/social/assets/fonts/roboto/Roboto-Bold.ttf
        - asset: packages/social/assets/fonts/roboto/Roboto-Light.ttf
        - asset: packages/social/assets/fonts/roboto/Roboto-Medium.ttf
        - asset: packages/social/assets/fonts/roboto/Roboto-Regular.ttf

    - family: YekanBakh
      fonts:
        - asset: packages/social/assets/fonts/yekanBakh/YekanBakhFaNum-Bold.ttf
        - asset: packages/social/assets/fonts/yekanBakh/YekanBakhFaNum-SemiBold.ttf
        - asset: packages/social/assets/fonts/yekanBakh/YekanBakhFaNum-Regular.ttf
        - asset: packages/social/assets/fonts/yekanBakh/YekanBakhFaNum-Light.ttf


  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
